### ISSUE TITLE
Add link to the description of the repo - Great and Inspiring Article

### ISSUE THREAD

**Issue by MeTaNoV** [distillpub/post--research-debt#3]
Is there any way to help with upcoming articles? Since the field is pretty large, which topic would you like to highlight in the future?

Cheers,
Pascal G. aka "The GeoloeG-IsT"

**Comment by MeTaNoV** [comment]
You can also add the link to the published article in the description of the repo like in https://github.com/distillpub/post--misread-tsne
It applies also to other article!

**Comment by colah** [comment]
Hi Pascal,

Thanks for pointing out the description issue -- I've added descriptions to all the repos.

I'm glad you're interested in Distill! We'll be updating the website with more details on contributing in the coming weeks.

Chris
