### ISSUE TITLE
"View all changes" link doesn't work

### ISSUE THREAD

**Issue by bfirsh** [distillpub/post--research-debt#5]
The link for the text "View all changes" [in the article](http://distill.pub/2017/research-debt/) points to http://distill.pub/2017/research-debt/undefined instead of the correct GitHub compare view.

[From the looks of the template](https://github.com/distillpub/template/blob/a85517e61b8d5be44f5f57154ccd1c7282b0d10f/components/appendix-distill.js#L8), it seems like `data.githubCompareUpdatesUrl` is not set. Searching for `githubCompareUpdatesUrl` on GitHub search brings up nothing, so presumably this is in a private configuration somewhere.

**Comment by ludwigschubert** [comment]
Thank you for noticing and digging so far into the issue! 

Fixed in 1a67729.
